language: go

go:
  - "1.8" 

# Specify which branches to build using a safelist
branches:
  only:
    - hugo

install:
  - go get github.com/spf13/hugo 

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  fqdn: blog.yuantops.com
  keep-history: true
  verbose: true
  on:
    branch: hugo