language: go

go:
  - "1.12" 

# Specify which branches to build using a safelist
branches:
  only:
    - hugo
    
install:
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - git checkout tags/v0.50
  - go install
  - cd $TRAVIS_BUILD_DIR
  - hugo version

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  fqdn: blog.yuantops.com
  keep-history: true
  on:
    branch: hugo
