language: go

go:
  - "1.12" 

# Specify which branches to build using a safelist
branches:
  only:
    - hugo
    
install:
  - OLD_DIR=$(pwd)
  - cd $HOME
  - mkdir $HOME/hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.50/hugo_0.50_Linux-64bit.tar.gz
  - tar -xzf hugo_0.50_Linux-64bit.tar.gz -C hugo
  - cd hugo
  - export PATH=$(pwd):$PATH
  - hugo version
  - cd ${OLD_DIR}

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  fqdn: blog.yuantops.com
  keep-history: true
  on:
    branch: hugo
