# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:title
relative_permalinks: true

# Setup
title:               Yuantops' Blog 
tagline:             'For the better good'
description:         '"How happy we are, to meet friends coming from far." --Confucious' 
url:                 http://blog.yuantops.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Yuan Yuan
  email:             yuan.tops@gmail.com

# Custom vars
version:             1.0.0
