#+author: yuan.tops@gmail.com
#+hugo_base_dir: ../
#+HUGO_SECTION: opinions
# Categories
#+filetags: @opinions
#+hugo_auto_set_lastmod: t

* 读书笔记                                                     :Reading:阅读:

** 2019阅读书单
:PROPERTIES:
:EXPORT_DATE: 2019-07-29T22:48:40
:EXPORT_HUGO_PUBLISHDATE: 2019-07-29T22:48:40
:EXPORT_FILE_NAME: 2019-my-reading-list
:EXPORT_DESCRIPTION: 2019年，我读完一本书，就把笔记写在这里。
:END:

今年我的工作有点变化，跳了一次槽，住处从杭州搬到深圳。深圳是个年轻城市，各种设施健全。没多久就发现，家附近步行十五分钟有一个社区图书站，与深圳图书馆总馆共享资源。从官网或微信公众号预约的书，两三天配送到站，晚上散步刚好顺便取回。虽然不是所有书都能预约，但已经很方便。

如此优越的借书条件，自然不能浪费。看来，今年阅读量一定可以达到历史最高水平。

*** 押沙龙，押沙龙！
- [[https://book.douban.com/subject/4619135/][豆瓣链接]]
- 个人评分: ☆☆☆☆☆
- 时间：<2019-11-05 Tue>

和它在图书馆偶遇，命中注定是我第一本福克纳。

《押沙龙, 押沙龙！》讲美国南部一个家族兴衰史，跨度包含南北战争。作者自述创作意图，“一个男人想得到一个儿子,结果得到的太多了,这些儿子又毁掉了他的故事”。男人是主人公萨德本，他有两子，查尔斯·邦和亨利，前者死于后者枪下。译者在译序里解释道，押沙龙是圣经人物，深受其父宠爱却屡次忤逆作乱，在西方语境里几乎与“逆子”“孽障”同义。书名预示着，故事会以悲剧收尾。

怀着崇拜心情，阅读这本作品。第一页就看得我气短：作者似乎打定主意不好好说话所以把句子写得特别长以至于一句话里包含很多短句而普通人不花一点功夫搞不明白要如何断句。通篇都是这种长句。读到第二章，故事好像和第一章对不上，原来是切换了视角。几乎每一章都有一个人口述，罗沙小姐、康普生先生、昆丁的大学室友，视角反复切换，每个人的叙述都只有部分，拼凑在一起，人物面貌、情节慢慢变清晰。所以，这本小说费脑子，没那么四平八稳。

除了叙述角度变换，故事时间线也很跳跃。罗沙小姐邀请昆丁同去老宅，萨德本初到镇上，萨德本发家史，亨利杀死查尔斯，罗沙小姐和昆丁到了老宅并发现其中秘密，罗沙小姐重新拜访老宅，这些故事往往彼此穿插，倒叙中带有插叙，需要一边读、一边梳理。读到下半段，整个家族兴衰轮廓已经展现在眼前，后续的叙述开始填充更多细节。譬如在第一章出现的罗沙小姐，她对萨德本充满怨恨，直到书后半段才知道，是因为萨德本侮辱性地向她提出了“先生出男孩才结婚”的建议，她觉得自己被冒犯。再比如，查尔斯·邦这个人物，在一半位置出场，然后他和亨利交往、和朱迪斯订婚，接着死于亨利枪下，但原因直到最后揭晓：亨利不能容忍他的黑人血统。此类伏笔，最后让人收获一种“恍然大悟”的快感。

回味这部小说，刻画人物很成功。朱迪斯的沉稳、坚强，查尔斯的敦厚、执着，都令人印象深刻。在全书浓重的悲剧氛围中，眼见萨德本百里地“起高楼，宴宾客，眼见它楼塌了!”，归结起来是萨德本人物性格使然。但与其说是他个人的悲剧，毋宁说是奴隶制瓦解前夕整个南方社会的悲剧。在小说结尾，施里夫问昆丁，你为什么恨南方。他激动地回答，不，我不恨！理智和情感的矛盾在这里爆发，颇有感染力(起码我被感染了)。

全书最后，作者大发慈悲，赐下一张人物编年表。感动！我刚看完第一遍，头脑昏沉之际发现这张宝图，仿佛得到通关密码，终于搞懂整个时间线。根据年表指引，再返过去重读。重读一遍，发现一些细节，还有一些迷糊。再重读一遍，又有豁然开朗之感。到此时，我已经对作者佩服得五体投地。看到一则趣闻，有人抱怨說(福克纳的作品),讀了三遍還不懂,福克納告誡他去讀第四遍。看来不止我一个人有此遭遇，很多读者都这样。

*** 乌纳穆诺中篇小说选
- [[https://book.douban.com/subject/26631626/][豆瓣链接]]
- 个人评分: ☆☆☆☆☆
- 时间：<2019-08-28 Wed>

去还书，站在书架前，这本西班牙小说有点突出。拿回家，前言就让我虎躯一震：作者乌纳穆诺身世特殊，是乱伦所生，他父亲居然是他母亲的亲舅舅！！_(¦3」∠)_

消化完这则人伦炸弹，接着读前言。译者介绍道，乌纳穆诺自己也饱受身世困扰，终其一生都在寻求心灵解脱，因此作品中多有哲学思考。读完全书，发现此言不假。

《亚伯 桑切斯：一种激情》讲一对兄弟彼此嫉妒、一生较劲，但又在对方中寻找自己的故事。故事母题，是圣经里亚伯和该隐。作者在小说里反复提到这则故事，我找到圣经原文:
#+BEGIN_QUOTE
该隐与他兄弟亚伯说话，二人正在田间，该隐起来打他兄弟亚伯，把他杀了。——《创世记 4:8》
#+END_QUOTE
华金医生嫉妒好友才华，几乎陷入病态。作家详细地描述了他嫉妒的心理和行为，入木三分。华金的女儿和亚伯的儿子亚伯林组建家庭，于是，不幸又延续到下一代。“两个家是两种令人悲哀的氛围，一是轻浮和冷漠，一是暗藏的、冰封的邪恶激情。”这是题目的来源。毫无疑问，一种激情指的是嫉妒。

《两个母亲》讲一个不育寡妇，安排情人和别的女人结婚生子，然后抢夺孩子的故事。故事很短，结局很惨。男主性格懦弱，被两个女人争夺，没有自我主张，不堪忍受折磨，跳崖死了。寡妇名为拉克尔，名字来源于圣经里的拉结，拉结不能生育。

《不折不扣一条汉子》讲一个美丽女儿被破产父亲“卖给”冰冷富豪，两人在相处中形成奇怪感情。丈夫“粗鲁而不可捉摸”，霸道总裁。妻子无比美丽，被丈夫降服，被丈夫迷惑，但是“她缺的是那爱的绝对确定性”。妻子感觉自己像受宠女奴，渴望得到超出附属物的对待。出于试探和挑衅，她出轨了。挑衅以失败告终，偷情的一对人被收拾得服服帖帖。但这位妻子也得以见到丈夫因暴怒而显露出的灵魂——丈夫爱他。最后，妻子死了，丈夫为她殉情。丈夫抑制在冰冷外表下的炽热火山，折磨妻子到死，又吞没自己。

《殉道者圣曼努埃尔　布埃诺》讲一个神甫掩饰谎言的一生。村里人都爱戴他，崇敬他。但是，他清醒明白自己职业的性质，内心深藏矛盾。他说，“是的，我知道，所谓的社会革命的那些头头里有一个说过，宗教是人民的鸦片。鸦片……鸦片……鸦片，是啊。让我们给他们鸦片，让他们安睡，让他们做美梦。我本人忙得不亦乐乎，也是在给自己鸦片啊。”一个能力超群的明眼人，做着民众拥护的事，内心却在煎熬，因为他认识到自己是在麻痹大众。他死后被村民当作圣人，教会也要册封他。这个故事给我印象很深，因为我想，一个人的实践和他的理想信念不一定百分百吻合，有的觉醒者会选择破坏、反抗，有的却会选择维持。后者有时会成为圣徒，但也要铭记前者。

*** 在华五十年
- [[https://www.douban.com/doubanapp/dispatch/book/4882116][豆瓣链接]]
- 时间: <2019-08-06 Tue>
- 来源: 社区自助图书站

在大陆受教育的人，肯定听过司徒雷登。我在杭州时，曾搜索杭城历史，知道他和杭州颇有渊源，死后连骸骨也安葬在杭州半山。但那时对他生平和事迹所知甚少，只知道是个美国人。读完这本书，才有了整体认识，改用敬意的眼光看他。我甚至感到遗憾：如果早半年看到这本书，定会去半山陵园瞻仰他。

这本书大致分三部分：少年与青年阶段，燕京大学阶段，驻华大使阶段。司徒雷登父母是在华传教士，他在杭州出生，可以说与中国非常有渊源。儿童时回到美国接受教育。他的宗教背景，推动他成为一名传教士，在选择未来传教地点时，经过一番内心纠结，最后选择来中国。

来华不久，他阴差阳错，开始负责筹建燕京大学。燕京大学的定位是一所教会大学，没有政府拨款，全靠同仁四处筹款。书中花了很大篇幅，介绍筹建细节：在美国找教会拨款、找基金会筹款、（甚至）找中国军阀和前清官员筹款买地。司徒雷登的个人能力在过程中得到了充分体现。燕京大学虽然是教会大学，但不保守刻板，在他主导下，宗教活动尽量不干扰校园秩序。正是由于他的开放胸襟，燕京大学为当时的中国培养了很多人才。司徒雷登因燕京大学赢得尊重，燕京大学与司徒雷登，算得上彼此成就。

在中国的舞台上，司徒雷登最后以驻华大使的身份谢幕。作为战后的美国大使，他接触各色政治人物，一直在国共两党间斡旋。国共重庆谈判，在书里着墨比较多。如果书里是真话，美国人真心对和谈成功抱有过希望。后续局势开始恶化，他们感到十分遗憾。历史上，被CCP蒙蔽的人太多，本国人尚且不能幸免，又怎能苛责外国人呢？等到江山变红，上海解放，他坐飞机离开，颇有一点狼狈。作为教育家，司徒雷登先生非常成功；相比之下，作为政治人物的成就，不知道差到哪里去了。

政治人物的回忆录，特别身处时代漩涡核心的人，谈到同一件历史大事，差异往往大得惊人。司徒雷登挺客气，对国内政客夸的多，贬的少（真是八面玲珑！）。但对于KMT官员，颇有一些负面评价。当时各个阶层都对KMT怨声载道，也说明了一点客观事实。

最后，我个人挺感兴趣的两个点：1)教会的教籍似乎和中国人的档案系统很类似。书中提到，开始他教籍所在教会不太友好，经常针对他在华传教活动发起异议，后来换了一个教会才消停。2)他与助手兼好友——傅泾波的终生友谊。傅泾波工作上一生为他服务，非常得力；在司徒雷登晚年卧床的时候，认真照顾他，如同家人。颇有点恩来同志的辅佐才干。

这本书翻译不觉拗口。看完去豆瓣翻评论，有人说大陆版颇有删节，已见怪不怪。待日后有机会再找原版读。

*** 全球首家交易所史话
- [[https://book.douban.com/subject/26953874/][豆瓣链接]]
- 时间: <2019-07-30 Tue>

去图书站还书，它正躺在书架上，刚好我那时在准备证券从业考试，便将它借回。

书名足够直观，讲的是全球首家证券交易所初期的一些故事。地点在荷兰阿姆斯特丹，作者围绕着东印度公司股票的发行、流通、交易，通过一些具体事例，展示了现代证券市场一些交易手法的萌芽形态。对我而言，这些概念原本是枯燥的、抽象的，通过历史事件的演绎，变得丰满、具体。书中介绍了好些证券行业术语，对加深理解很有帮助：

- 《愤怒的投资者》: *远期交易*, *裸卖空*
- 《第一次繁荣》: *做市商*, *股票交易所*, *郁金香狂热*
- 《犹太裔商人》: *经纪人* , *投机商*
- 《交易俱乐部》: *证券抵押贷款(回购)*, *中央结算*
- 《投机交易》: *期权*

作为刚转行证券业的新手，虽然故事里的金额有些算不太清楚，但仍不失故事本身的趣味。如果一个读者完全没有金融背景，单单拓宽眼界也是好的。

最后，说一些不足之处：
1. 翻译水平一般。以P176为例，"萨尔瓦多通过东印度公司的会计将一份价值3000荷兰盾的股票转入摩恩斯的账户作为贷款抵押品"，结合上下文，这里的"价值3000荷兰盾"应该是票面价值。不知原文如何用词，译文应该注明为好。
2. 原文最后没有介绍全球首个证券交易所的结局，有些不圆满。维基百科上，阿姆斯特丹证券交易所[[https://zh.wikipedia.org/wiki/%25E9%2598%25BF%25E5%25A7%2586%25E6%2596%25AF%25E7%2589%25B9%25E4%25B8%25B9%25E8%25AF%2581%25E5%2588%25B8%25E4%25BA%25A4%25E6%2598%2593%25E6%2589%2580][中文词条]]是这么说的:
   #+BEGIN_QUOTE
   2000年9月22日，阿姆斯特丹证券交易所与布鲁塞尔证券交易所和巴黎证券交易所合并成立了欧洲证券交易所。
   #+END_QUOTE

** TODO 我的多抓鱼书单                                                          :Emacs:

* 杂俎                                                                          :Reality:
