#+author: yuan.tops@gmail.com
#+hugo_base_dir: ../
#+HUGO_SECTION: opinions
# Categories
#+filetags: @opinions
#+hugo_auto_set_lastmod: t

* 读书笔记                                                     :Reading:阅读:

** 2019阅读书单
:PROPERTIES:
:EXPORT_DATE: 2019-07-29T22:48:40
:EXPORT_HUGO_PUBLISHDATE: 2019-07-29T22:48:40
:EXPORT_FILE_NAME: 2019-my-reading-list
:EXPORT_DESCRIPTION: 2019年，我读完一本书，就把笔记写在这里。
:END:

今年我的工作有点变化，跳了一次槽，住处也从杭州搬到深圳。深圳是个年轻城市，各种设施健全。没多久就发现，家附近步行十五分钟有一个社区图书站，与深圳图书馆总馆共享资源。从官网或微信公众号预约的书，两三天即配送到站，晚上散步刚好顺便取回。虽然不是所有书都能预约，但已经很方便。

如此优越的借书条件，自然不能浪费。看来，今年阅读量一定可以达到历史最高水平。

*** 在华五十年
- [[https://www.douban.com/doubanapp/dispatch/book/4882116][豆瓣链接]]
- 时间: <2019-08-06 Tue>
- 来源: 社区自助图书站

在大陆受教育的人，肯定听过司徒雷登。我在杭州时，曾搜索杭城历史，知道他和杭州颇有渊源，死后连骸骨也安葬在杭州半山。但那时对他生平和事迹所知甚少，只知道是个美国人。读完这本书，才有了整体认识，改用敬意的眼光看他。我甚至感到遗憾：如果早半年看到这本书，定会去半山陵园瞻仰他。

这本书大致分三部分：少年与青年阶段，燕京大学阶段，驻华大使阶段。司徒雷登父母是在华传教士，他在杭州出生，可以说与中国非常有渊源。儿童时回到美国接受教育。他的宗教背景，推动他成为一名传教士，在选择未来传教地点时，经过一番内心纠结，最后选择来中国。

来华不久，他阴差阳错，开始负责筹建燕京大学。燕京大学的定位是一所教会大学，没有政府拨款，全靠同仁四处筹款。书中花了很大篇幅，介绍筹建细节：在美国找教会拨款、找基金会筹款、（甚至）找中国军阀和前清官员筹款买地。司徒雷登的个人能力在过程中得到了充分体现。燕京大学虽然是教会大学，但不保守刻板，在他主导下，宗教活动尽量不干扰校园秩序。正是由于他的开放胸襟，燕京大学为当时的中国培养了很多人才。司徒雷登因燕京大学赢得尊重，燕京大学与司徒雷登，算得上彼此成就。

在中国的舞台上，司徒雷登最后以驻华大使的身份谢幕。作为战后的美国大使，他接触各色政治人物，一直在国共两党间斡旋。国共重庆谈判，在书里着墨比较多。如果书里是真话，美国人真心对和谈成功抱有过希望。后续局势开始恶化，他们感到十分遗憾。历史上，被CCP蒙蔽的人太多，本国人尚且不能幸免，又怎能苛责外国人呢？等到江山变红，上海解放，他坐飞机离开，颇有一点狼狈。作为教育家，司徒雷登先生非常成功；相比之下，作为政治人物的成就，不知道差到哪里去了。

政治人物的回忆录，特别身处时代漩涡核心的人，谈到同一件历史大事，差异往往大得惊人。司徒雷登挺客气，对国内政客夸的多，贬的少（真是八面玲珑！）。但对于KMT官员，颇有一些负面评价。当时各个阶层都对KMT怨声载道，也说明了一点客观事实。

最后，我个人挺感兴趣的两个点：1)教会的教籍似乎和中国人的档案系统很类似。书中提到，开始他教籍所在教会不太友好，经常针对他在华传教活动发起异议，后来换了一个教会才消停。2)他与助手兼好友——傅泾波的终生友谊。傅泾波工作上一生为他服务，非常得力；在司徒雷登晚年卧床的时候，认真照顾他，如同家人。颇有点恩来同志的辅佐才干。

这本书翻译不觉拗口。看完去豆瓣翻评论，有人说大陆版颇有删节，已见怪不怪。待日后有机会再找原版读。

*** 全球首家交易所史话
- [[https://book.douban.com/subject/26953874/][豆瓣链接]]
- 时间: <2019-07-30 Tue>

去图书站还书，它正躺在书架上，刚好我那时在准备证券从业考试，便将它借回。

书名足够直观，讲的是全球首家证券交易所初期的一些故事。地点在荷兰阿姆斯特丹，作者围绕着东印度公司股票的发行、流通、交易，通过一些具体事例，展示了现代证券市场一些交易手法的萌芽形态。对我而言，这些概念原本是枯燥的、抽象的，通过历史事件的演绎，变得丰满、具体。书中介绍了好些证券行业术语，对加深理解很有帮助：

- 《愤怒的投资者》: *远期交易*, *裸卖空*
- 《第一次繁荣》: *做市商*, *股票交易所*, *郁金香狂热*
- 《犹太裔商人》: *经纪人* , *投机商*
- 《交易俱乐部》: *证券抵押贷款(回购)*, *中央结算*
- 《投机交易》: *期权*

作为刚转行证券业的新手，虽然故事里的金额有些算不太清楚，但仍不失故事本身的趣味。如果一个读者完全没有金融背景，单单拓宽眼界也是好的。

最后，说一些不足之处：
1. 翻译水平一般。以P176为例，"萨尔瓦多通过东印度公司的会计将一份价值3000荷兰盾的股票转入摩恩斯的账户作为贷款抵押品"，结合上下文，这里的"价值3000荷兰盾"应该是票面价值。不知原文如何用词，译文应该注明为好。
2. 原文最后没有介绍全球首个证券交易所的结局，有些不圆满。维基百科上，阿姆斯特丹证券交易所[[https://zh.wikipedia.org/wiki/%25E9%2598%25BF%25E5%25A7%2586%25E6%2596%25AF%25E7%2589%25B9%25E4%25B8%25B9%25E8%25AF%2581%25E5%2588%25B8%25E4%25BA%25A4%25E6%2598%2593%25E6%2589%2580][中文词条]]是这么说的:
   #+BEGIN_QUOTE
   2000年9月22日，阿姆斯特丹证券交易所与布鲁塞尔证券交易所和巴黎证券交易所合并成立了欧洲证券交易所。
   #+END_QUOTE

** TODO 我的多抓鱼书单                                                          :Emacs:

* 杂俎                                                                          :Reality:
